### ISSUE TITLE
Shrink python package.

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/meta-phosphor#13]
11824   /usr/lib/python2.7
1504    /usr/lib/libpython2.7.so.1.0
676 /usr/lib/python2.7/lib-dynload/unicodedata.so

Do we need to install *.py or just *.pyc.  Can we do some build-time processing to ensure everything is pyc?

```
root@qemuarm:/usr# find -name "*.pyc" | wc -l
301
root@qemuarm:/usr# find -name "*.py" | wc -l
313
```

**Comment by shenki** [comment]
Python 3?

**Comment by williamspatrick** [comment]
@shenki - Can you elaborate? Is python 3 smaller?  We would need to ensure all the python applications and modules we want to use support python 3 before making that leap.

**Comment by williamspatrick** [comment]
Issue moved to [openbmc/openbmc #221](https://github.com/openbmc/openbmc/issues/221) via [**ZenHub.io**](https://www.zenhub.io/)
